# Change these first
owner: CERIT-SC # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: CERIT-SC Rancher - Kubernetes Management Portal
    url: https://rancher.cloud.e-infra.cz
    icon: https://raw.githubusercontent.com/CERIT-SC/uptime/master/icon/rancher.svg
  - name: CERIT-SC Kubernetes Cluster - Kuba Public
    url: http://kuba-pub.cerit-sc.cz
  - name: CERIT-SC User Documentation
    url: https://docs.cerit.io
  - name: CERIT-SC Container Registry - cerit.io
    url: https://cerit.io
  - name: CERIT-SC Gitlab - Git and CI/CD service
    url: https://gitlab.ics.muni.cz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cerit.io
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for CERIT-SC webpages."
  introMessage: This is a status page for uptime time of CERIT-SC services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
