# Change these first
owner: CERIT-SC # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: CERIT-SC Rancher -- Kubernetes Management Portal
    url: https://rancher.cloud.e-infra.cz
    icon: https://raw.githubusercontent.com/CERIT-SC/uptime/master/icon/rancher.svg
  - name: CERIT-SC Kubernetes Cluster -- Kuba Public
    url: http://kuba-pub.cerit-sc.cz
    icon: https://raw.githubusercontent.com/CERIT-SC/uptime/master/icon/rke2.svg
    expectedStatusCodes:
      - 200
      - 201
      - 302
      - 404
  - name: CERIT-SC User Documentation
    url: https://docs.cerit.io
  - name: CERIT-SC Container Registry -- cerit.io
    url: https://cerit.io
    icon: https://github.com/CERIT-SC/uptime/raw/master/icon/Moby-logo.png
  - name: CERIT-SC Gitlab -- Git and CI/CD service
    url: https://gitlab.ics.muni.cz
    icon: https://raw.githubusercontent.com/CERIT-SC/uptime/master/icon/gitlab.svg
  - name: Zabbix Monitoring System
    url: https://zabbix.cerit-sc.cz/
    icon: https://assets.zabbix.com/img/favicon.ico
  - name: Task Execution Service K8s -- TESK
    url: https://tesk-prod.cloud.e-infra.cz/swagger-ui/index.html
    icon: https://raw.githubusercontent.com/elixir-cloud-aai/TESK/master/documentation/img/TESKlogowfont.png
  - name: Workflow Execution Service K8s -- WES
    url: https://wes-prod.cloud.e-infra.cz/ga4gh/wes/v1/ui/
  - name: Jupyter HUB
    url: https://hub.cloud.e-infra.cz/
    icon: https://hub.cloud.e-infra.cz/hub/logo
  - name: Binder HUB
    url: https://binderhub.cloud.e-infra.cz/
    icon: https://binderhub.readthedocs.io/en/latest/_static/logo.png
  - name: e-INFRA CZ OpenStack site in Brno
    url: https://identity.cloud.muni.cz/v3/
    icon: https://raw.githubusercontent.com/CERIT-SC/uptime/master/icon/openstack.png
    headers:
      - "Content-Type: application/json"
  - name: e-INFRA CZ OpenStack site in Ostrava
    url: https://identity.ostrava.openstack.cloud.e-infra.cz/v3/
    headers:
      - "Content-Type: application/json"
    icon: https://raw.githubusercontent.com/CERIT-SC/uptime/master/icon/openstack.png
  - name: EOSC Indico
    url: https://events.eosc.cz
    icon: https://indico.cern.ch/images/logo_indico.png
  - name: EOSC Survey Platform
    url: https://survey.eosc.cz
    icon: https://www.limesurvey.org/templates/limesurvey/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cerit.io
  #baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for CERIT-SC webpages."
  introMessage: This is a status page for uptime time of CERIT-SC services.
  navbar:
    - title: Status
      href: /
    - title: CERIT-SC User Documentation
      href: https://docs.cerit.io
    - title: CERIT-SC Rancher
      href: https://rancher.cloud.e-infra.cz

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
